project-name: OpenTTD
primary-language: en
css:
  - /static/truewiki/truewiki.css
  - /static/css/openttd.css
favicon: /static/favicon.ico
license:
  GNU Free Documentation License
html-snippets:
  header: |
    <div id="openttd-logo">
        <div id="openttd-logo-text"><a href="/en/"><img src="/static/img/layout/openttd-logo.png" alt="OpenTTD" /></a></div>
    </div>
  footer: |
    <a href="https://www.openttd.org/policy.html">Privacy Policy</a> |
    <a href="https://www.openttd.org/contact.html">Contact</a> |
