project-name: OpenTTD
primary-language: en
css:
  - /static/truewiki/truewiki.css
  - /static/css/openttd.css
favicon: /static/favicon.ico
license:
  GNU Free Documentation License
html-snippets:
  header: |
    <a id="openttd-logo" href="/en/">
        <div id="openttd-logo-text"><img src="/static/img/layout/openttd-logo.png" alt="OpenTTD" /></div>
    </a>
  footer: |
    <a href="https://www.openttd.org/policy.html">Privacy Policy</a> |
    <a href="https://www.openttd.org/contact.html">Contact</a> |
